beginningSchedule: 'Fri Sep 6 2024'
botOldLineupMessage: '

âš ï¸ This was the lineup for mystic creatures festival âš ï¸

'
botMotd: 'Hello, welcome to this unofficial lineUp bot for mystic creatures festival, few infos:

- You can search for DJ sets by typing their names

- You can use the red or green dots below for disabling/enabling DJ changes notifications

- Here is the web app url: <a href="https://shallowbunny.com/">shallowbunny.com</a> (Save it to your homescreen so it works offline)

- @bigSisyBot is a similar bot running for Sisyphos

- You can share this bot to your contacts using <a href="https://t.me/share/url?url=https%3A%2F%2Ft.me%2F%40shallowBunnyBot&text=Check%20out%20this%20awesome%20bot%21">this share link</a> 

- You can pin the bot for easy access (similar to saved messages)

Have fun! ğŸ˜˜' 

meta:
 nowShowShallowBunnyAd: false
 nowShowDataSourceAd: false
 nowShowSisyDuckAd: false
 nowTextAfterMap: "shallowbunny.com is an unofficial lineup web app, now running for mystic creatures festival âš ï¸âš ï¸âš ï¸ data is beeing uploaded âš ï¸âš ï¸âš ï¸"
 nowTextWhenFinished: "shallowbunny.com is a festival (unofficial) lineup web app"
 nowSubmitPR: ""
 #"https://github.com/shallowBunny/shallowbunny.com"
 botUrl:  "https://t.me/shallowBunnyBot"
 aboutBigIcon: "bunny-192x192.png"
 aboutShowShallowBunnyIcon: false
 aboutShowSisyDuckIcon: true
 nowMapImage: ""
 roomYouAreHereEmoticon: 'ğŸ°'
 mobileAppName: "Shallow Bunny"
 prefix: "bunny"
 title: "mystic creatures festival lineup"

nbDaysForInput: 3
buttons: ["Now", "ALL", "Help"]
nowSkipClosed: false
input: false

lineup:
  rooms:
    - "ğŸ§™ Mystic ground"
    - "ğŸ§Œ Creatures Corner"
    - "ğŸŒ² Freaky Forest"
    - "ğŸª Comic circus"
  #  - "ğŸª© Funky Float"
  #  - "ğŸ¦„ Spirit Space"
  #  - "ğŸ–¨ Others"
  sets:
    "ğŸ§™ Mystic ground":
      - day: 0
        dj: Vogti
        hour: 17
        minute: 0
      - day: 0
        dj: SYN3K
        hour: 19
        minute: 0
      - day: 0
        dj: Konfusia
        hour: 20
        minute: 30
      - day: 0
        dj: Jan Oberlaender
        hour: 22
        minute: 30
      - day: 1
        dj: Space 92
        hour: 0
        minute: 30
      - day: 1
        dj: Maurice Mino & sin:port
        hour: 2
        minute: 30
      - day: 1
        dj: TiM TASTE
        hour: 4
        minute: 30
        duration: 120
      - day: 1
        dj: Zweisamt
        hour: 14
        minute: 0
      - day: 1
        dj: Ezio Aguiar
        hour: 16
        minute: 0
      - day: 1
        dj: Elias DorÃ©
        hour: 17
        minute: 30
      - day: 1
        dj: Stan Kolev
        hour: 19
        minute: 30
      - day: 1
        dj: Pauli Pocket
        hour: 21
        minute: 30
      - day: 1
        dj: Pleasure Island
        hour: 23
        minute: 30
      - day: 2
        dj: Carbon
        hour: 1
        minute: 30
      - day: 2
        dj: Aio
        hour: 3
        minute: 30
      - day: 2
        dj: Atlantik
        hour: 5
        minute: 30
        duration: 90
      - day: 2
        dj: WAYHNA
        hour: 13
        minute: 0
      - day: 2
        dj: She Knows
        hour: 15
        minute: 0
      - day: 2
        dj: Just Emma
        hour: 16
        minute: 30
      - day: 2
        dj: Extrawelt
        hour: 18
        minute: 30
      - day: 2
        dj: Naicet & Elias Goldmund
        hour: 20
        minute: 0
      - day: 2
        dj: Township Rebellion
        hour: 22
        minute: 0
      - day: 3
        dj: Kalayo Fire Crew
        hour: 0
        minute: 0
        duration: 60        
    "ğŸ§Œ Creatures Corner": 
      - day: 0
        dj: RotkÃ¤ppchen Candy
        hour: 15
        minute: 0
      - day: 0
        dj: EloiÃŸ
        hour: 17
        minute: 0
      - day: 0
        dj: Acado
        hour: 18
        minute: 30
      - day: 0
        dj: Ãœberhaupt & AuÃŸerdem
        hour: 20
        minute: 0
      - day: 0
        dj: Corios
        hour: 22
        minute: 0
      - day: 0
        dj: le.fu
        hour: 23
        minute: 30
      - day: 1
        dj: Max Marlon
        hour: 1
        minute: 0
      - day: 1
        dj: KotterzÃ¼r
        hour: 2
        minute: 30
      - day: 1
        dj: Tadoh
        hour: 4
        minute: 30
      - day: 1
        dj: Deep Ã„ndi
        hour: 6
        minute: 0
      - day: 1
        dj: Christian HÃ¼lshoff
        hour: 7
        minute: 0
      - day: 1
        dj: Herrhausen & Treindl
        hour: 8
        minute: 0
      - day: 1
        dj: Seyde
        hour: 9
        minute: 0
      - day: 1
        dj: Robinson Schmuso
        hour: 10
        minute: 0
      - day: 1
        dj: Pacaya
        hour: 11
        minute: 30
      - day: 1
        dj: Lotte Ahoi
        hour: 13
        minute: 0
      - day: 1
        dj: Martha van Straaten
        hour: 15
        minute: 0
      - day: 1
        dj: Pulli & Chomba
        hour: 17
        minute: 0
      - day: 1
        dj: Horst Haller
        hour: 19
        minute: 0
      - day: 1
        dj: KÃ¤ptin 12 & DÃ¼sentrieb
        hour: 20
        minute: 30
      - day: 1
        dj: Flave
        hour: 22
        minute: 30
      - day: 1
        dj: Frida Darko
        hour: 23
        minute: 30
      - day: 2
        dj: UREM
        hour: 1
        minute: 30        
      - day: 2
        dj: R3NATA
        hour: 3
        minute: 30
      - day: 2
        dj: Kapoor
        hour: 5
        minute: 0
      - day: 2
        dj: Ninze & Niju
        hour: 7
        minute: 0
      - day: 2
        dj: WOJTEK
        hour: 9
        minute: 0
      - day: 2
        dj: Lazy LÃ³rres
        hour: 10
        minute: 0
      - day: 2
        dj: Late Night Jockel Session with HuGs
        hour: 11
        minute: 3
      - day: 2
        dj: Heimlich KnÃ¼ller
        hour: 13
        minute: 30
      - day: 2
        dj: Kahl & Karmena
        hour: 15
        minute: 30
      - day: 2
        dj: Caleesi & Sarah Kreis
        hour: 17
        minute: 30
      - day: 2
        dj: Mira
        hour: 19
        minute: 30
      - day: 2
        dj: Tvisker
        hour: 21
        minute: 30
      - day: 2
        dj: Nico Tober
        hour: 23
        minute: 0
      - day: 3
        dj: "[Lu:wes] b2b RenA aka [ais]"
        hour: 0
        minute: 30
      - day: 3
        dj: Najesh & ArtÃ¯soko
        hour: 2
        minute: 0
      - day: 3
        dj: Pia Pan & Heyoka
        hour: 4
        minute: 0
      - day: 3
        dj: Nugi & Kollektiv Sheesh
        hour: 6
        minute: 0
      - day: 3
        dj: Lemonella
        hour: 8
        minute: 0
      - day: 3
        dj: neoBeo
        hour: 10
        minute: 0
      - day: 3
        dj: Trippin Jaguar
        hour: 12
        minute: 0
      - day: 3
        dj: Zen Baboon
        hour: 14
        minute: 0
        duration: 120
    "ğŸŒ² Freaky Forest":
      - day: 0
        dj: Jungspund
        hour: 20
        minute: 0
      - day: 0
        dj: Diladi
        hour: 22
        minute: 0
      - day: 0
        dj: Blake Strange
        hour: 23
        minute: 30
      - day: 1
        dj: Joseph Disco
        hour: 1
        minute: 0
      - day: 1
        dj: Kolja Broxi
        hour: 3
        minute: 0
      - day: 1
        dj: Marco Liebreiz
        hour: 4
        minute: 30
      - day: 1
        dj: LaBerg
        hour: 6
        minute: 0
      - day: 1
        dj: Tonda
        hour: 7
        minute: 30
      - day: 1
        dj: RakÃ¤the
        hour: 9
        minute: 0
      - day: 1
        dj: Babes2bass
        hour: 10
        minute: 30
      - day: 1
        dj: The One Million Butt Show
        hour: 12
        minute: 30
      - day: 1
        dj: Lisa Filou
        hour: 14
        minute: 30
      - day: 1
        dj: Schwirri
        hour: 16
        minute: 0
      - day: 1
        dj: BARTi
        hour: 17
        minute: 30
      - day: 1
        dj: Schmackofatz & Spinneratz
        hour: 19
        minute: 0
      - day: 1
        dj: Flanko
        hour: 21
        minute: 0
      - day: 1
        dj: Taberia
        hour: 23
        minute: 0
      - day: 2
        dj: Sabura
        hour: 0
        minute: 30
      - day: 2
        dj: Onory
        hour: 2
        minute: 30
      - day: 2
        dj: Phauna
        hour: 4
        minute: 0
      - day: 2
        dj: SÃ¶rÃ¶s
        hour: 5
        minute: 30
      - day: 2
        dj: Savethedisco
        hour: 7
        minute: 30
      - day: 2
        dj: Secret
        hour: 9
        minute: 0
      - day: 2
        dj: Langstrumpf
        hour: 10
        minute: 30
      - day: 2
        dj: Zhart
        hour: 12
        minute: 0
      - day: 2
        dj: Lazy Hazy
        hour: 13
        minute: 30
      - day: 2
        dj: Taqtik
        hour: 15
        minute: 0
      - day: 2
        dj: Bisu b2b MaKa
        hour: 17
        minute: 0
      - day: 2
        dj: Melbo & Falke
        hour: 19
        minute: 0
      - day: 2
        dj: Pilocka Krach
        hour: 21
        minute: 0
      - day: 2
        dj: SILSAN
        hour: 23
        minute: 0
      - day: 3
        dj: Yooni
        hour: 0
        minute: 30
      - day: 3
        dj: SIRU
        hour: 2
        minute: 0
      - day: 3
        dj: Mira VÃ¡na
        hour: 3
        minute: 30
      - day: 3
        dj: Planet Caravan
        hour: 5
        minute: 0
      - day: 3
        dj: Antaares
        hour: 6
        minute: 30
        duration: 60
    "ğŸª Comic circus":
      - day: 0
        dj: Nat Gohl
        hour: 19
        minute: 30
      - day: 0
        dj: "Andy's Echo"
        hour: 21
        minute: 30
      - day: 0
        dj: Sassafras Tree
        hour: 23
        minute: 0
      - day: 1
        dj: Oberst & Buchner
        hour: 1
        minute: 0
      - day: 1
        dj: F.I.E.L.D.Y
        hour: 3
        minute: 0
      - day: 1
        dj: Rafa'EL
        hour: 4
        minute: 30
      - day: 1
        dj: CJ Art
        hour: 6
        minute: 0
      - day: 1
        dj: Natanael Megersa
        hour: 7
        minute: 30
        duration: 90
      - day: 1
        dj: Sensual Playfight
        hour: 10
        minute: 0
      - day: 1
        dj: Zumba with Hannah
        hour: 12
        minute: 0
      - day: 1
        dj: Kiezchor
        hour: 13
        minute: 0
      - day: 1
        dj: Hans From Space
        hour: 14
        minute: 0
      - day: 1
        dj: Midas 104
        hour: 15
        minute: 30
        duration: 90
      - day: 1
        dj: Stavroz
        hour: 18
        minute: 0
      - day: 1
        dj: Mimi Love
        hour: 19
        minute: 30
      - day: 1
        dj: Tummentott
        hour: 21
        minute: 30
      - day: 2
        dj: Mona Pirzad
        hour: 23
        minute: 30
      - day: 2
        dj: Mad Son
        hour: 1
        minute: 0
      - day: 2
        dj: katzenhold
        hour: 2
        minute: 30        
      - day: 2
        dj: Moritz Butschek
        hour: 4
        minute: 0        
      - day: 2
        dj: Robin Schellenberg
        hour: 5
        minute: 30
      - day: 2
        dj: Jawwa
        hour: 7
        minute: 30
        duration: 90        
      - day: 2
        dj: "Creatures Out of Cages: Celebrating Your Weirdness Ritual"
        hour: 10
        minute: 0
      - day: 2
        dj: Drumming Workshop with Awal Idaris
        hour: 11
        minute: 30
      - day: 2
        dj: Twerkshop
        hour: 13
        minute: 0
        duration: 60
      - day: 2
        dj: Saraabb
        hour: 14
        minute: 30
      - day: 2
        dj: Swaytone
        hour: 16
        minute: 0
      - day: 2
        dj: Mcfly
        hour: 17
        minute: 30
      - day: 2
        dj: ShangoMx
        hour: 19
        minute: 0
      - day: 2
        dj: Under Damascus
        hour: 20
        minute: 30
      - day: 2
        dj: Karlo Kurbel
        hour: 22
        minute: 0
      - day: 2
        dj: Esther Silex & Madmotorique
        hour: 23
        minute: 30
      - day: 3
        dj: Prismode & Solvane
        hour: 1
        minute: 30
      - day: 3
        dj: CREAM
        hour: 3
        minute: 30
      - day: 3
        dj: Lamadeus
        hour: 5
        minute: 0
      - day: 3
        dj: Etzo
        hour: 6
        minute: 30
      - day: 3
        dj: Faulchen FÃ¤nther
        hour: 8
        minute: 0
      - day: 3
        dj: Nur Simon
        hour: 9
        minute: 30
      - day: 3
        dj: Crescendo Berlin
        hour: 11
        minute: 30
        duration: 60